spring:
  datasource:
    # 数据库信息
    url: jdbc:mysql://localhost:3306/ccp_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: Penistrong
    password: chenliwei
    # 注意mysql.connector.java的版本, 5.X低版本(适用于MySQL 5.X版本)使用com.mysql.jdbc.Driver, 6.X版本往上使用com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # IDEA报Warning:Can not resolve configuration property "xxx" 没有关系，只是无法识别自定义的配置
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        # 启用监控
        enabled: true
        # 路径 即输入context_path + url-pattern即可访问DruidStatViewPage
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,66.42.66.135
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: chenliwei

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 294323192648-nuvj58l0ub4dksa03mgtnfe2abcpj2vg.apps.googleusercontent.com
            client-secret: Tj8YT5OB4ZXdb-RPHnt-hWrG

  mvc:
    format:
      date: yyyy-MM-dd

